### ISSUE TITLE
Mongo db duplicate doc error

### ISSUE THREAD

**Issue by mylastore** [koajs/json-error#49]
When there is a: MongoError: E11000 duplicate I get this error. How can I handle this a bit better? 
```
{
    "message": "Not Found",
    "name": "NotFoundError",
    "stack": "NotFoundError: Not Found\n    at Object.throw (/media/phil/Backup/sys/seoblog/api/node_modules/koa/lib/context.js:97:11)\n    at /media/phil/Backup/sys/seoblog/api/node_modules/koa-json-error/lib/middleware.js:52:58\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "status": 404
}
```

**Comment by mylastore** [comment]
nevermind it was my bad implementation when throwing an error ;)
